Updated Russian localization
lilypuree/Decorative-Blocks pull request #71
Opened 2022-04-28 21:00 UTC by syorito-hatsuki

My team made free translation fixes for u mod. I hope players be happy to play in their own language :3

Sincerely, Project Manager of the Enthusiasm Dev Team

2022-04-28 22:19 UTC, Aizistral requested changes
As an independent bearer of Russian language, I evaluate those fixes as overall acceptable, with the exclusion of third change being entirely unnecessary.

2022-04-28 22:19 UTC, Aizistral commented on Common/src/main/resources/assets/decorative_blocks/lang/ru_ru.json
> +  "block.decorative_blocks.jungle_palisade": "Частокол из Тропического дерева",
Я бы не писал это с большой буквы, в ванильной локализации так не принято

2022-04-28 22:26 UTC, syorito-hatsuki commented on Common/src/main/resources/assets/decorative_blocks/lang/ru_ru.json
> +  "block.decorative_blocks.jungle_palisade": "Частокол из Тропического дерева",
Спасибо что приметил, видемо парни опечатались. Надо будет лучше делать проверку перед заливом.

2022-04-28 22:28 UTC, syorito-hatsuki commented on Common/src/main/resources/assets/decorative_blocks/lang/ru_ru.json
> +  "block.decorative_blocks.jungle_palisade": "Частокол из Тропического дерева",
> Я бы не писал это с большой буквы, в ванильной локализации так не принято

Поправил

2022-04-28 22:45 UTC, syorito-hatsuki commented on Common/src/main/resources/assets/decorative_blocks/lang/ru_ru.json
> +  "block.decorative_blocks.jungle_palisade": "Частокол из Тропического дерева",
> Я бы не писал это с большой буквы, в ванильной локализации так не принято

Скорее всего ребята запутались в стилях. Ибо в английском все блоки пишутся "Я Такой то Блок Из Той то Руды". А в русском в нижнем регистре. Приметил что у нас половина переводов по стилю отличаются, где то РУ стиль, где-то АНГ стиль. Завтра подниму это на митинге)

2022-04-29 08:21 UTC, Aizistral approved these changes
Looks good to me 👍

2022-07-01 00:48 UTC, closed without merging